[phases.setup]
nixPkgs = ["python39Full", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn streamz_backend.wsgi:application --bind 0.0.0.0:$PORT"
